from enum import IntEnum
from typing import List, Optional, Sequence, TypedDict

__version__: str
DEFAULT_CLIENT_JOINT_STATE_UDP_PORT: int
DEFAULT_CLIENT_ROBOT_STATE_UDP_PORT: int
DEFAULT_SERVER_IP: str
JOINT_COUNT: int


class MotionState(IntEnum):
    LyingDown: int
    StandingUp: int
    Passive: int
    SitDown: int
    Motion: int


class MotionGait(IntEnum):
    Walk: int
    Bipedal: int
    Flip: int
    WalkPhase: int
    PoseTracking: int
    Running: int


class LegOdom(TypedDict):
    velocity_body: List[float]
    position: List[float]
    orientation: List[float]
    angular_velocity: List[float]


class RequestRobotState:
    def __init__(self) -> None: ...
    def __enter__(self) -> "RequestRobotState": ...
    def __exit__(self, exc_type, exc, tb) -> bool: ...
    def connect(self) -> bool: ...
    def disconnect(self) -> None: ...
    def setRobotIp(self, ip: str) -> None: ...
    def setRobotStateUploadPort(self, port: int) -> None: ...
    def setRobotStateUploadRate(self, rate_hz: int) -> None: ...
    def setTcpLocalPort(self, port: int) -> None: ...
    def setSessionId(self, session_id: int) -> None: ...
    def getRobotVersion(self) -> Optional[tuple[int, int, int, int, int, int]]: ...
    def queryRobotVersion(self) -> Optional[tuple[int, int, int, int, int, int]]: ...
    def getJointPosition(self) -> Optional[List[float]]: ...
    def getJointVelocity(self) -> Optional[List[float]]: ...
    def getJointTorque(self) -> Optional[List[float]]: ...
    def getImuRpy(self) -> Optional[List[float]]: ...
    def getImuQuat(self) -> Optional[List[float]]: ...
    def getImuAcc(self) -> Optional[List[float]]: ...
    def getImuOmega(self) -> Optional[List[float]]: ...
    def getLegOdom(self) -> Optional[LegOdom]: ...
    def getMotorTemperature(self) -> Optional[List[float]]: ...
    def getDriverTemperature(self) -> Optional[List[float]]: ...
    def getCurrentMotionState(self) -> Optional[int]: ...
    def getCurrentGait(self) -> Optional[int]: ...
    def getLastMotionState(self) -> Optional[int]: ...
    def getLastGait(self) -> Optional[int]: ...
    def getSubGait(self) -> Optional[int]: ...
    def getMaxVelocity(self) -> Optional[List[float]]: ...
    def getBatteryLevel(self) -> Optional[int]: ...
    def getBatteryCurrent(self) -> Optional[float]: ...
    def getJointStateTimestamp(self) -> Optional[int]: ...
    def getImuTimestamp(self) -> Optional[int]: ...
    def getOdometryTimestamp(self) -> Optional[int]: ...
    def getMotionStateTimestamp(self) -> Optional[int]: ...
    def getBatteryTimestamp(self) -> Optional[int]: ...


class MotionLevelControl(RequestRobotState):
    def setMotionCommandRate(self, rate_hz: int) -> None: ...
    def setVelocityControlFlag(self, enabled: bool) -> None: ...
    def setZeroPositionsFlag(self) -> None: ...
    def setWalk(self) -> None: ...
    def setRunning(self) -> None: ...
    def setLeftFlip(self) -> None: ...
    def setRightFlip(self) -> None: ...
    def setBipedal(self) -> None: ...
    def setInvBipedal(self) -> None: ...
    def setPronk(self) -> None: ...
    def setPace(self) -> None: ...
    def setBound(self) -> None: ...
    def setVelocity(self, x: float, y: float, yaw: float) -> bool: ...
    def setStandUp(self) -> bool: ...
    def setSitDown(self) -> bool: ...
    def setDamping(self) -> bool: ...


class JointLevelControl(RequestRobotState):
    def setJointStateUploadPort(self, port: int) -> None: ...
    def setJointCommand(
        self,
        kp: Sequence[float],
        pos: Sequence[float],
        kd: Sequence[float],
        vel: Sequence[float],
        tff: Sequence[float],
    ) -> bool: ...
    def setJointKp(self, kp: Sequence[float]) -> bool: ...
    def setJointPosition(self, pos: Sequence[float]) -> bool: ...
    def setJointKd(self, kd: Sequence[float]) -> bool: ...
    def setJointVelocity(self, vel: Sequence[float]) -> bool: ...
    def setJointTorqueFeedForward(self, tff: Sequence[float]) -> bool: ...
    def setZeroJointCommand(self) -> bool: ...
    def getJointPositionHighRate(self) -> Optional[List[float]]: ...
    def getJointVelocityHighRate(self) -> Optional[List[float]]: ...
    def getJointTorqueHighRate(self) -> Optional[List[float]]: ...
    def getImuRpyHighRate(self) -> Optional[List[float]]: ...
    def getImuQuatHighRate(self) -> Optional[List[float]]: ...
    def getImuAccHighRate(self) -> Optional[List[float]]: ...
    def getImuOmegaHighRate(self) -> Optional[List[float]]: ...
    def getJointStateTimestampHighRate(self) -> Optional[float]: ...
    def getJointStateSeqHighRate(self) -> Optional[int]: ...
